<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'acceptable_sugar_versions' => 
  array (
    0 => '9.*.*',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => '',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Studio4BusinessCenter',
  'published_date' => '2020-02-12 09:48:17',
  'type' => 'module',
  'version' => 1581500898,
  'remove_tables' => 'false',
);


$installdefs = array (
  'id' => 'Studio4BusinessCenter',

  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/BusinessCenters/metadata/studio.php',
      'to' => 'custom/modules/BusinessCenters/metadata/studio.php',
    ),
  ),

);